# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.10.0"

pre_release = true

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.11/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
ZFS: 2.3.2
qemu-guest-agent: 10.0.2
fuse: 3.17.2
nut: 2.8.3
Tailscale: 1.84.0
Linux firmware: 20250509
metal-agent: 0.1.3
Intel u-code: 20250512
wasmedge: 0.6.0
Kata containers: 3.17.0
NVIDIA LTS: 535.247.01
NVIDIA Production: 570.140.08
NVIDIA Container Toolkit: 1.17.8
"""

    [notes.youki]
        title = "Youki Container Runtime"
        description = """\
[Youki](https://github.com/youki-dev/youki) is now supported as a container runtime.
"""

    [notes.tenstorrent]
        title = "Tenstorrent drivers"
        description = """\
[Tennstorrent](https://github.com/tenstorrent/tt-kmd) driver is now supported as an extension.
"""

    [notes.hailort]
        title = "HailoRT drivers"
        description = """\
[HailoRT](https://github.com/hailo-ai/hailort-drivers) driver is now supported as an extension.
"""

[make_deps]
