# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.10.3"

pre_release = false

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.10/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
qemu-guest-agent: 10.0.2
Tailscale: 1.84.0
Intel u-code: 20250512
wasmedge: 0.6.0
Kata containers: 3.17.0
NVIDIA LTS: 535.247.01
NVIDIA Production: 570.140.08
NVIDIA Container Toolkit: 1.17.8
"""

[make_deps]
