# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.10.0"

pre_release = false

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.10/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
ZFS: 2.3.2
gvisor: 20250505
Kata containers: 3.16.0
Tailscale: 1.82.5
NVIDIA LTS: 535.247.01
NVIDIA Production: 570.133.20
NVIDIA Container Toolkit: 1.17.6
"""

[make_deps]
